# This class is generated by podio_crm:model
class PodioTeacher < ActiveRecord::Base
  belongs_to :teacher
  attr_accessible           :name,
    :email,
    :subject_area_s,
    :faculty_oplerno_email,
    :physical_address,
    :country_of_citizenship,
    :phone_number,
    :i_permit_oplerno_to_list_my_name_alongside_any_courses_i_create_on_their_website_s,
    :oplerno_rep_contact,
    :date_last_contacted_note_type_of_contact_in_comments_section,
    :course_proposal_progress,
    :linkedin,



    def name=(value)
      self.field_68472121 = value
  end
  def name
    self.field_68472121
  end

  def email=(value)
    self.field_68472122 = value
  end
  def email
    self.field_68472122
  end

  def subject_area_s=(value)
    self.field_68472123 = value
  end
  def subject_area_s
    self.field_68472123
  end

  def faculty_oplerno_email=(value)
    self.field_68472124 = value
  end
  def faculty_oplerno_email
    self.field_68472124
  end

  def physical_address=(value)
    self.field_68472125 = value
  end
  def physical_address
    self.field_68472125
  end

  def country_of_citizenship=(value)
    self.field_68472126 = value
  end
  def country_of_citizenship
    self.field_68472126
  end

  def phone_number=(value)
    self.field_68472127 = value
  end
  def phone_number
    self.field_68472127
  end

  def i_permit_oplerno_to_list_my_name_alongside_any_courses_i_create_on_their_website_s=(value)
    self.field_68472128 = value
  end
  def i_permit_oplerno_to_list_my_name_alongside_any_courses_i_create_on_their_website_s
    self.field_68472128
  end

  def oplerno_rep_contact=(value)
    self.field_68472129 = value
  end
  def oplerno_rep_contact
    self.field_68472129
  end

  def date_last_contacted_note_type_of_contact_in_comments_section=(value)
    self.field_68472130 = value
  end
  def date_last_contacted_note_type_of_contact_in_comments_section
    self.field_68472130
  end

  def course_proposal_progress=(value)
    self.field_68472131 = value
  end
  def course_proposal_progress
    self.field_68472131
  end

  def linkedin=(value)
    self.field_68472132 = value
  end
  def linkedin
    self.field_68472132
  end

end
